<a href="https://colab.research.google.com/github/zhuminghui17/Duke_CS_590_Project/blob/main/CS590_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# !pip install sodapy

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sodapy import Socrata

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting sodapy
  Downloading sodapy-2.2.0-py2.py3-none-any.whl (15 kB)
Collecting requests>=2.28.1
  Downloading requests-2.28.2-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 KB 2.4 MB/s eta 0:00:00
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests>=2.28.1->sodapy) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests>=2.28.1->sodapy) (2022.12.7)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.8/dist-packages (from requests>=2.28.1->sodapy) (3.0.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests>=2.28.1->sodapy) (1.24.3)
Installing collected packages: requests, sodapy
  Attempting uninstall: requests
    Found existing installation: requests 2.25.1
    Uninstalling requests-2.25.1:
      Successfully uninstalled requests-2.25.1
Successfully installed requests-2.28.2 sodapy-2.2.0

In [ ]:
## Loading the dataset from the website API to df format
# Limit to 100,000 dataset for now. Around 2 min time to call for 1 million data (can imagine how long for 300 million)

# DO NOT CHANGE THIS ONE: OBTAINED PRIVATE TOKEN TO ACCESS API
# Unauthenticated client only works with public data sets. Note 'None'
# in place of application token, and no username or password:
client = Socrata('data.cityofchicago.org',
                  'HvwA24CQ9KirQgVKAtYWA6LTA',
                  username="ma510@duke.edu",
                  password="Tryhard100%")


# First 1000000 results, returned as JSON from API / converted to Python list of
# dictionaries by sodapy.

# Options:
# 1) Try to find a way to load all 300.000.000 data (hard)
# 2) Try to random-draw 3.000.000 data (so have have representative dataset)

results = client.get("m6dm-c72p", order = False, limit = 20000)

# Alternative: looping through some var or index, and combine later (can be done using loop, probably) -- use maybe day as modifiers
# results = client.get("m6dm-c72p", order = True, where = 'trip_seconds == 1', limit = 100000)


# Convert to pandas DataFrame
results_df = pd.DataFrame.from_records(results)

In [ ]:
results_df

,trip_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_census_tract,dropoff_census_tract,pickup_community_area,dropoff_community_area,fare,...,additional_charges,trip_total,shared_trip_authorized,trips_pooled,pickup_centroid_latitude,pickup_centroid_longitude,pickup_centroid_location,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_centroid_location
0,d40d1efd03b4514b173c6ca221e7e1def0932989,2019-02-05T14:30:00.000,2019-02-05T14:45:00.000,949,4.07151453685077,17031841900,17031840300,28,59,10,...,2.55,12.55,False,1,41.8679024175,-87.6429586652,"{'type': 'Point', 'coordinates': [-87.64295866...",41.8335178865,-87.6813558293,"{'type': 'Point', 'coordinates': [-87.68135582..."
1,d40d1f50c4c4834fb7303b4b25af34bbc0c29cbf,2019-03-28T18:30:00.000,2019-03-28T18:30:00.000,492,1.44364253095898,17031031400,17031061901,3,6,5,...,2.55,7.55,False,1,41.962178629,-87.6453787624,"{'type': 'Point', 'coordinates': [-87.64537876...",41.9432371225,-87.6434709559,"{'type': 'Point', 'coordinates': [-87.64347095..."
2,d40d2056865c3b8aa5bb54c281bf0a6da8312b31,2019-01-18T19:15:00.000,2019-01-18T19:30:00.000,337,1.07631495872,17031081402,17031081202,8,8,5,...,8.15,15.15,False,1,41.8919715078,-87.6129454143,"{'type': 'Point', 'coordinates': [-87.61294541...",41.9027880476,-87.6261455896,"{'type': 'Point', 'coordinates': [-87.62614558..."
3,d40d2066f56fad16a52622ebc54a53394fd765ef,2019-03-06T05:00:00.000,2019-03-06T05:15:00.000,1448,12.1996750382476,NaN,NaN,31,21,17.5,...,2.55,20.05,False,1,41.8502663663,-87.667569312,"{'type': 'Point', 'coordinates': [-87.66756931...",41.9386661962,-87.7112105933,"{'type': 'Point', 'coordinates': [-87.71121059..."
4,d40d20ba60636d1a1f658eb9979e3e6254accf8d,2019-02-13T22:30:00.000,2019-02-13T22:45:00.000,711,4.3484816674889,17031832500,17031081700,7,8,7.5,...,2.55,10.05,False,1,41.9218774613,-87.6640782395,"{'type': 'Point', 'coordinates': [-87.66407823...",41.8920421365,-87.6318639497,"{'type': 'Point', 'coordinates': [-87.63186394..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,d4338c1d8627f56da24cfbbdc7de46200d5ab6b9,2019-01-30T16:30:00.000,2019-01-30T17:30:00.000,3152,24.1558751618814,17031031400,NaN,3,NaN,22.5,...,2.55,25.05,True,4,41.962178629,-87.6453787624,"{'type': 'Point', 'coordinates': [-87.64537876...",NaN,NaN,NaN
19996,d4338c30ccce34c5508a0d9ac1c88b71f1a9bb3a,2019-01-20T22:30:00.000,2019-01-20T22:45:00.000,857,6.85942915628695,17031280100,17031040600,28,4,12.5,...,2.55,16.05,False,1,41.8853000224,-87.6428084655,"{'type': 'Point', 'coordinates': [-87.64280846...",41.9668340674,-87.6840183712,"{'type': 'Point', 'coordinates': [-87.68401837..."
19997,d4338e2bcf0e8c5619d4ff1195091d74f4906ac8,2018-12-10T16:00:00.000,2018-12-10T16:30:00.000,1884,6.29569679376,NaN,NaN,24,3,15,...,2.5,17.5,False,1,41.9012069941,-87.6763559892,"{'type': 'Point', 'coordinates': [-87.67635598...",41.96581197,-87.6558787862,"{'type': 'Point', 'coordinates': [-87.65587878..."
19998,d4338f07bd75c133cd0b212f0c24737952e910df,2019-03-09T02:15:00.000,2019-03-09T02:45:00.000,1698,11.9903228084421,NaN,NaN,7,66,20,...,2.55,22.55,False,1,41.9226862843,-87.6494887289,"{'type': 'Point', 'coordinates': [-87.64948872...",41.7718485152,-87.695666342,"{'type': 'Point', 'coordinates': [-87.69566634..."
19999,d4338f87dbdcf2de1f96c7ecf49c095d9b9e2262,2019-01-26T13:45:00.000,2019-01-26T14:00:00.000,881,3.21651629696,17031071000,17031050900,7,5,7.5,...,2.55,10.05,False,1,41.9217014922,-87.6559118484,"{'type': 'Point', 'coordinates': [-87.65591184...",41.9449467539,-87.6857782135,"{'type': 'Point', 'coordinates': [-87.68577821..."

In [ ]:
# TODO Upload other dataset: Weather Dataset (@Layan)

InvalidURL: ignored

In [ ]:
# TODO: Upload other dataset: Stock market condition during the day

In [ ]:
# What do we actually want to find:
# - group the data into date -> make summary of trend on tipping, carpooling, and fare/km.
# - frequency of rides at different time in the day (24 hours)
# - tipping percentage by region/longitude of pickup/dropoff location

NameError: ignored

In [ ]:
# Some methods to partition the dataset
# Writing all different CSV files, splitting stuff. 1 Million obs for each.

chunk_size= 1000000
batch_no=1

for chunk in pd.read_csv("D:\coding project\cs590\Trips.csv", chunksize=chunk_size,iterator=True):
    name = "D:\coding project\cs590\Trips" + str(batch_no) + ".csv"
    chunk.to_csv(name, header= col2)
    batch_no = batch_no + 1
    print('index: {}'.format(batch_no))

In [ ]:
# Creating the semi-random sampling methods
# Reading CSV files and sampling from each. The number of obs we will have depending on the number of the sample.

df_pool = pd.DataFrame()

for i in range(1, 301):
    
    # Reading the dataset one by one
    print("Reading the dataset number " + str(i))
    name = "D:\coding project\cs590\Trips" + str(i) + ".csv"
    df = pd.read_csv(name)
    
    # Summarizing the dataset with date groups
    
    # Partition the dataset randomly from sample (3 million obs for now, can be increased quite readily)
    df_sample = df.sample(n = 10000)
    df_pool = pd.concat([df_pool, df_sample])
    
df_pool.to_csv("D:\coding project\cs590\TripsRandomSample.csv")

In [ ]:
# Create aggregate summary for each iteration (combined later)
# Reading CSV files and attempt to create an average for each indicators on daily groupby
# Main variables to create average of:
# Trip seconds
# Trip miles
# Fare
# Tip
# Tip as percentage of (Fare + Additional Charge)
# Trips pooled
# Shared Trip Authorized

df_summary = pd.DataFrame()

for i in range(1, 301):
    
    # Reading the dataset one by one
    print("Reading the dataset number " + str(i))
    name = "D:\coding project\cs590\Trips" + str(i) + ".csv"
    df = pd.read_csv(name)
    
     #create "date" and "hours timestamp as base for mean"
    df['date'] = df['Trip Start Timestamp'].str[:10]    
    df['time_start'] = df['Trip Start Timestamp'].str[11:16]
    df['ampm'] = df['Trip Start Timestamp'].str[-2:]
    df['count'] = 1
    
    # Create tip as percentage of fare
    df['tipperc'] = df['Tip'] / (df['Fare'] + df['Additional Charges'])
    
    # Create the summary count of data
    df_summary = pd.concat([df_summary, df.groupby('date').agg({'Trip Seconds': 'mean', 'Fare': 'mean', 'Trip Miles': 'mean', 
                                                               'Tip': 'mean', 'tipperc': 'mean', 'Shared Trip Authorized': 'mean',
                                                               'count' : 'sum'})])
    
df_summary.to_csv("D:\coding project\cs590\TripsMeanStreaming.csv")

## Minghui

In [6]:
url = 'https://github.com/zhuminghui17/Duke_CS_590_Project/blob/1414ad2fd5116955c70a3f17064d942b15592cd4/dropped.csv'
df = pd.read_csv(url, skiprows=2)

ParserError: ignored

In [15]:
import pandas as pd
df = pd.read_csv('TripsRandomSample.csv')

In [16]:
df.shape

(3000000, 23)

In [24]:
df = df.drop(['Unnamed: 0', 'Unnamed: 0.1', 'Trip ID'], axis = 1)

In [25]:
df.columns

Index(['Trip Start Timestamp', 'Trip End Timestamp', 'Trip Seconds',
       'Trip Miles', 'Pickup Census Tract', 'Dropoff Census Tract',
       'Pickup Community Area', 'Dropoff Community Area', 'Fare', 'Tip',
       'Additional Charges', 'Trip Total', 'Shared Trip Authorized',
       'Trips Pooled', 'Pickup Centroid Latitude', 'Pickup Centroid Longitude',
       'Pickup Centroid Location', 'Dropoff Centroid Latitude',
       'Dropoff Centroid Longitude', 'Dropoff Centroid Location'],
      dtype='object')

In [28]:
from pathlib import Path

file = Path('dropped.csv')
print(file.stat().st_size)

718472453

In [27]:
df.to_csv('dropped.csv')

In [2]:
import pandas as pd
df = pd.read_csv('dropped.csv')
# 7 secs to read

FileNotFoundError: ignored

In [30]:
df

,Unnamed: 0,Trip Start Timestamp,Trip End Timestamp,Trip Seconds,Trip Miles,Pickup Census Tract,Dropoff Census Tract,Pickup Community Area,Dropoff Community Area,Fare,...,Additional Charges,Trip Total,Shared Trip Authorized,Trips Pooled,Pickup Centroid Latitude,Pickup Centroid Longitude,Pickup Centroid Location,Dropoff Centroid Latitude,Dropoff Centroid Longitude,Dropoff Centroid Location
0,0,03/24/2019 10:30:00 AM,03/24/2019 10:45:00 AM,790.0,5.6,NaN,NaN,48.0,53.0,10.0,...,2.55,12.55,False,1,41.729676,-87.572717,POINT (-87.5727171342 41.7296764229),41.673820,-87.635740,POINT (-87.6357397768 41.6738199043)
1,1,03/12/2019 10:15:00 AM,03/12/2019 10:30:00 AM,568.0,1.4,1.703128e+10,1.703108e+10,28.0,8.0,5.0,...,2.55,9.55,False,1,41.885300,-87.642808,POINT (-87.6428084655 41.8853000224),41.895033,-87.619711,POINT (-87.6197106717 41.8950334495)
2,2,03/19/2019 08:15:00 AM,03/19/2019 08:30:00 AM,593.0,2.5,1.703148e+10,1.703184e+10,48.0,44.0,7.5,...,2.55,10.05,False,1,41.729199,-87.587986,POINT (-87.5879864909 41.7291990754),41.742488,-87.630045,POINT (-87.6300448953 41.7424875717)
3,3,03/21/2019 05:45:00 PM,03/21/2019 06:00:00 PM,1398.0,2.4,1.703183e+10,1.703108e+10,28.0,8.0,5.0,...,2.55,7.55,True,4,41.885281,-87.657233,POINT (-87.6572331997 41.8852813201),41.892042,-87.631864,POINT (-87.6318639497 41.8920421365)
4,4,02/01/2019 08:45:00 PM,02/01/2019 09:00:00 PM,706.0,2.7,1.703108e+10,1.703106e+10,8.0,6.0,7.5,...,0.00,8.50,True,2,41.907520,-87.626659,POINT (-87.6266589003 41.9075200747),41.934659,-87.646730,POINT (-87.6467297286 41.9346591566)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2999995,2999995,01/26/2019 01:45:00 AM,01/26/2019 01:45:00 AM,215.0,1.0,1.703108e+10,1.703183e+10,8.0,7.0,2.5,...,2.55,5.05,False,1,41.907492,-87.635760,POINT (-87.6357600901 41.9074919303),41.914747,-87.654007,POINT (-87.6540070286 41.9147473049)
2999996,2999996,03/01/2019 07:45:00 PM,03/01/2019 08:00:00 PM,376.0,1.3,1.703107e+10,1.703107e+10,7.0,7.0,5.0,...,2.55,7.55,False,1,41.921855,-87.646211,POINT (-87.6462109769 41.9218549112),41.914616,-87.631717,POINT (-87.6317173661 41.9146162864)
2999997,2999997,03/04/2019 04:45:00 AM,03/04/2019 05:15:00 AM,1382.0,15.6,1.703106e+10,1.703198e+10,6.0,76.0,20.0,...,7.55,27.55,False,1,41.936159,-87.661265,POINT (-87.6612652184 41.936159071),41.979071,-87.903040,POINT (-87.9030396611 41.9790708201)
2999998,2999998,01/07/2019 09:00:00 AM,01/07/2019 09:30:00 AM,2138.0,7.4,1.703138e+10,1.703184e+10,38.0,32.0,12.5,...,2.55,15.05,True,2,41.820574,-87.614986,POINT (-87.6149864759 41.8205743953),41.880994,-87.632746,POINT (-87.6327464887 41.8809944707)
2999999,2999999,03/11/2019 06:00:00 AM,03/11/2019 06:15:00 AM,1124.0,6.9,1.703184e+10,1.703108e+10,30.0,8.0,12.5,...,6.20,19.70,False,1,41.853835,-87.693539,POINT (-87.6935387966 41.853834685),41.899156,-87.626211,POINT (-87.6262105324 41.8991556134)

In [39]:
from datetime import datetime
import pytz
from dateutil import parser

chicago_timezone = pytz.timezone('America/Chicago')

for i in ['Start', 'End']:
  df[f'Trip {i} UTC'] = df[f'Trip {i} Timestamp'].apply(lambda x: datetime.strptime(x, '%m/%d/%Y %I:%M:%S %p'))
  df[f'Trip {i} UTC'] = df[f'Trip {i} UTC'].apply(lambda x: pytz.utc.localize(x))
  df[f'Trip {i} Chicago'] = df[f'Trip {i} UTC'].apply(lambda x: x.astimezone(chicago_timezone))

In [65]:
df['Date'] = df['Trip Start Chicago'].apply(lambda x: str(x)[:10])
df['Hour'] = df['Trip Start Chicago'].apply(lambda x: int(str(x)[11:13]))

In [103]:
df

,Unnamed: 0,Trip Start Timestamp,Trip End Timestamp,Trip Seconds,Trip Miles,Pickup Census Tract,Dropoff Census Tract,Pickup Community Area,Dropoff Community Area,Fare,...,Pickup Centroid Location,Dropoff Centroid Latitude,Dropoff Centroid Longitude,Dropoff Centroid Location,Trip Start UTC,Trip Start Chicago,Trip End UTC,Trip End Chicago,Date,Hour
0,0,03/24/2019 10:30:00 AM,03/24/2019 10:45:00 AM,790.0,5.6,NaN,NaN,48.0,53.0,10.0,...,POINT (-87.5727171342 41.7296764229),41.673820,-87.635740,POINT (-87.6357397768 41.6738199043),2019-03-24 10:30:00+00:00,2019-03-24 05:30:00-05:00,2019-03-24 10:45:00+00:00,2019-03-24 05:45:00-05:00,2019-03-24,5
1,1,03/12/2019 10:15:00 AM,03/12/2019 10:30:00 AM,568.0,1.4,1.703128e+10,1.703108e+10,28.0,8.0,5.0,...,POINT (-87.6428084655 41.8853000224),41.895033,-87.619711,POINT (-87.6197106717 41.8950334495),2019-03-12 10:15:00+00:00,2019-03-12 05:15:00-05:00,2019-03-12 10:30:00+00:00,2019-03-12 05:30:00-05:00,2019-03-12,5
2,2,03/19/2019 08:15:00 AM,03/19/2019 08:30:00 AM,593.0,2.5,1.703148e+10,1.703184e+10,48.0,44.0,7.5,...,POINT (-87.5879864909 41.7291990754),41.742488,-87.630045,POINT (-87.6300448953 41.7424875717),2019-03-19 08:15:00+00:00,2019-03-19 03:15:00-05:00,2019-03-19 08:30:00+00:00,2019-03-19 03:30:00-05:00,2019-03-19,3
3,3,03/21/2019 05:45:00 PM,03/21/2019 06:00:00 PM,1398.0,2.4,1.703183e+10,1.703108e+10,28.0,8.0,5.0,...,POINT (-87.6572331997 41.8852813201),41.892042,-87.631864,POINT (-87.6318639497 41.8920421365),2019-03-21 17:45:00+00:00,2019-03-21 12:45:00-05:00,2019-03-21 18:00:00+00:00,2019-03-21 13:00:00-05:00,2019-03-21,12
4,4,02/01/2019 08:45:00 PM,02/01/2019 09:00:00 PM,706.0,2.7,1.703108e+10,1.703106e+10,8.0,6.0,7.5,...,POINT (-87.6266589003 41.9075200747),41.934659,-87.646730,POINT (-87.6467297286 41.9346591566),2019-02-01 20:45:00+00:00,2019-02-01 14:45:00-06:00,2019-02-01 21:00:00+00:00,2019-02-01 15:00:00-06:00,2019-02-01,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2999995,2999995,01/26/2019 01:45:00 AM,01/26/2019 01:45:00 AM,215.0,1.0,1.703108e+10,1.703183e+10,8.0,7.0,2.5,...,POINT (-87.6357600901 41.9074919303),41.914747,-87.654007,POINT (-87.6540070286 41.9147473049),2019-01-26 01:45:00+00:00,2019-01-25 19:45:00-06:00,2019-01-26 01:45:00+00:00,2019-01-25 19:45:00-06:00,2019-01-25,19
2999996,2999996,03/01/2019 07:45:00 PM,03/01/2019 08:00:00 PM,376.0,1.3,1.703107e+10,1.703107e+10,7.0,7.0,5.0,...,POINT (-87.6462109769 41.9218549112),41.914616,-87.631717,POINT (-87.6317173661 41.9146162864),2019-03-01 19:45:00+00:00,2019-03-01 13:45:00-06:00,2019-03-01 20:00:00+00:00,2019-03-01 14:00:00-06:00,2019-03-01,13
2999997,2999997,03/04/2019 04:45:00 AM,03/04/2019 05:15:00 AM,1382.0,15.6,1.703106e+10,1.703198e+10,6.0,76.0,20.0,...,POINT (-87.6612652184 41.936159071),41.979071,-87.903040,POINT (-87.9030396611 41.9790708201),2019-03-04 04:45:00+00:00,2019-03-03 22:45:00-06:00,2019-03-04 05:15:00+00:00,2019-03-03 23:15:00-06:00,2019-03-03,22
2999998,2999998,01/07/2019 09:00:00 AM,01/07/2019 09:30:00 AM,2138.0,7.4,1.703138e+10,1.703184e+10,38.0,32.0,12.5,...,POINT (-87.6149864759 41.8205743953),41.880994,-87.632746,POINT (-87.6327464887 41.8809944707),2019-01-07 09:00:00+00:00,2019-01-07 03:00:00-06:00,2019-01-07 09:30:00+00:00,2019-01-07 03:30:00-06:00,2019-01-07,3
2999999,2999999,03/11/2019 06:00:00 AM,03/11/2019 06:15:00 AM,1124.0,6.9,1.703184e+10,1.703108e+10,30.0,8.0,12.5,...,POINT (-87.6935387966 41.853834685),41.899156,-87.626211,POINT (-87.6262105324 41.8991556134),2019-03-11 06:00:00+00:00,2019-03-11 01:00:00-05:00,2019-03-11 06:15:00+00:00,2019-03-11 01:15:00-05:00,2019-03-11,1

In [116]:
import requests
import json
from datetime import datetime

import matplotlib.pyplot as plt

import pandas as pd
import numpy as np
from pandas import Series, DataFrame

# 1. Make an API call and store the response.
def getWeatherInfo(lat, long, date, hour):
  url = f'https://archive-api.open-meteo.com/v1/archive?latitude={lat}' \
        +f'&longitude={long}&start_date={date}&end_date={date}&hourly=temperature_2m' \
        +'&hourly=temperature_2m,relativehumidity_2m,precipitation,rain,snowfall,' \
        +'windspeed_10m,winddirection_10m&timezone=America%2FChicago'
  try:
    data = requests.get(url)
    data = data.json()
    weatherInfo = {
    'tempHourly': data['hourly']['temperature_2m'][hour],
    'precipitationHourly': data['hourly']['precipitation'][hour],
    'rainHourly': data['hourly']['rain'][hour],
    'snowfallHourly': data['hourly']['snowfall'][hour],
    'winspeedHourly': data['hourly']['windspeed_10m'][hour],
    'windirectionHourly': data['hourly']['winddirection_10m'][hour]}
    return weatherInfo
  except:
    return data.json()

In [117]:
import time
def addWeatherInfo(data):
  startTime = time.time()
  # generate empty columns
  for i in ['tempHourly', 'precipitationHourly', 'rainHourly', 'snowfallHourly', 'winspeedHourly', 'windirectionHourly']:
    data[i] = pd.Series()
  try:
    for i in range(len(data)):
      if (i+1) % 10000 == 0:
        currTime = time.time()
        print(f'Completed Obs: {(i*10000)}/3000000, Current Process: {round((i*10000)/3000000 * 100, 3)}%, Time Spent: {currTime-startTime}')
      info = getWeatherInfo(data['Pickup Centroid Latitude'][i], data['Pickup Centroid Longitude'][i], data['Date'][i], data['Hour'][i])
      for j in ['tempHourly', 'precipitationHourly', 'rainHourly', 'snowfallHourly', 'winspeedHourly', 'windirectionHourly']:
        data.at[i, j] = info[j]
  except:
    print(i)
  return data

In [118]:
dataHaveWeather = addWeatherInfo(df[:20])

<ipython-input-117-a506d107dd3d>:6: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  data[i] = pd.Series()
<ipython-input-117-a506d107dd3d>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[i] = pd.Series()

10

In [1]:
df

NameError: ignored