In [24]:
# loading the normal package and the dataset
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from datetime import datetime

In [13]:
# dx = pd.read_csv(r"C:\Users\avior\Box\CS_590_Projects\dataWithWeather.csv")
df = pd.read_csv(r"C:\Users\avior\Box\CS_590_Projects\dataWithCommunityInfo.csv")

df_2 = df.copy()

In [15]:
np.sum(pd.isna(df))

# around 230k missing data for pickup and dropoff
# we will not be dropping that

Unnamed: 0                          0
Unnamed: 0.1                        0
Unnamed: 0.1.1                      0
Trip Start Timestamp                0
Trip End Timestamp                  0
Trip Seconds                     2233
Trip Miles                         68
Pickup Census Tract           1166086
Dropoff Census Tract          1175456
Pickup Community Area          220344
Dropoff Community Area         239458
Fare                             1508
Tip                              1507
Additional Charges               1509
Trip Total                       1509
Shared Trip Authorized              0
Trips Pooled                        0
Pickup Centroid Latitude       215874
Pickup Centroid Longitude      215874
Pickup Centroid Location       215874
Dropoff Centroid Latitude      235372
Dropoff Centroid Longitude     235372
Dropoff Centroid Location      235372
Trip Start UTC                      0
Trip Start Chicago                  0
Trip End UTC                        0
Trip End Chicago                    0
Date                                0
Hour                                0
time                                0
temperature_2m (°C)                 0
relativehumidity_2m (%)             0
precipitation (mm)                  0
rain (mm)                           0
snowfall (cm)                       0
cloudcover (%)                      0
windspeed_10m (km/h)                0
winddirection_10m (°)               0
Pickup Community Name          220344
PopPickup                      220344
IncomePickup                   220344
CarpoolPerCommPickup           220344
Dropoff Community Name         239458
PopDropoff                     239458
IncomeDropoff                  239458
CarpoolPerCommDropoff          239458
dtype: int64

In [19]:
# We use dx as the lastest one, but dropping only observation that is unreasonable

df_2['Tip_percent_PerRide'] = (df_2['Tip']/(df_2['Fare'] + df_2['Additional Charges']))*100
df_2['count'] = 1
df_2['Tipped'] = (df_2['Tip'] > 0)

df = df_2.dropna(subset=['Trip Seconds', 'Tip', 'Trip Miles', 'Fare', 'Tip_percent_PerRide','Trip Total'])

In [18]:
np.sum(pd.isna(df_2))

Unnamed: 0                          0
Unnamed: 0.1                        0
Unnamed: 0.1.1                      0
Trip Start Timestamp                0
Trip End Timestamp                  0
Trip Seconds                        0
Trip Miles                          0
Pickup Census Tract           1164679
Dropoff Census Tract          1174074
Pickup Community Area          220006
Dropoff Community Area         239140
Fare                                0
Tip                                 0
Additional Charges                  0
Trip Total                          0
Shared Trip Authorized              0
Trips Pooled                        0
Pickup Centroid Latitude       215538
Pickup Centroid Longitude      215538
Pickup Centroid Location       215538
Dropoff Centroid Latitude      235056
Dropoff Centroid Longitude     235056
Dropoff Centroid Location      235056
Trip Start UTC                      0
Trip Start Chicago                  0
Trip End UTC                        0
Trip End Chicago                    0
Date                                0
Hour                                0
time                                0
temperature_2m (°C)                 0
relativehumidity_2m (%)             0
precipitation (mm)                  0
rain (mm)                           0
snowfall (cm)                       0
cloudcover (%)                      0
windspeed_10m (km/h)                0
winddirection_10m (°)               0
Pickup Community Name          220006
PopPickup                      220006
IncomePickup                   220006
CarpoolPerCommPickup           220006
Dropoff Community Name         239140
PopDropoff                     239140
IncomeDropoff                  239140
CarpoolPerCommDropoff          239140
Tip_percent_PerRide                 0
count                               0
Tipped                              0
dtype: int64

In [21]:
df

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,Trip Start Timestamp,Trip End Timestamp,Trip Seconds,Trip Miles,Pickup Census Tract,Dropoff Census Tract,Pickup Community Area,...,PopPickup,IncomePickup,CarpoolPerCommPickup,Dropoff Community Name,PopDropoff,IncomeDropoff,CarpoolPerCommDropoff,Tip_percent_PerRide,count,Tipped
0,0,0,0,03/24/2019 10:30:00 AM,03/24/2019 10:45:00 AM,790.0,5.6,NaN,NaN,48.0,...,13088.0,35883.58973,0.087571,West Pullman,26104.0,22615.25200,0.132105,0.000000,1,False
1,1,1,3142,03/24/2019 10:15:00 AM,03/24/2019 10:30:00 AM,664.0,5.8,1.703183e+10,1.703108e+10,3.0,...,57182.0,42111.65248,0.038842,Near North Side,105481.0,105016.51420,0.028290,15.936255,1,True
2,2,2,4320,03/24/2019 10:15:00 AM,03/24/2019 10:30:00 AM,1034.0,4.6,NaN,NaN,19.0,...,78116.0,21611.65496,0.132300,West Town,87781.0,68810.35002,0.048778,0.000000,1,False
3,3,3,7361,03/24/2019 10:30:00 AM,03/24/2019 11:00:00 AM,2061.0,17.6,1.703108e+10,1.703198e+10,8.0,...,105481.0,105016.51420,0.028290,O'Hare,13418.0,35578.00231,0.087412,15.360983,1,True
4,4,4,10135,03/24/2019 10:15:00 AM,03/24/2019 10:15:00 AM,503.0,1.2,1.703108e+10,1.703108e+10,8.0,...,105481.0,105016.51420,0.028290,Near North Side,105481.0,105016.51420,0.028290,0.000000,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2999995,2999995,2999995,2704179,12/21/2022 02:00:00 AM,12/21/2022 02:00:00 AM,421.0,2.4,NaN,NaN,24.0,...,87781.0,68810.35002,0.048778,West Town,87781.0,68810.35002,0.048778,0.000000,1,False
2999996,2999996,2999996,2704564,12/21/2022 02:00:00 AM,12/21/2022 02:00:00 AM,183.0,0.9,1.703183e+10,1.703183e+10,28.0,...,67881.0,59634.86515,0.042375,Near West Side,67881.0,59634.86515,0.042375,0.000000,1,False
2999997,2999997,2999997,2705872,12/21/2022 02:00:00 AM,12/21/2022 02:15:00 AM,409.0,2.0,NaN,NaN,32.0,...,42298.0,90269.15221,0.018143,Near West Side,67881.0,59634.86515,0.042375,0.000000,1,False
2999998,2999998,2999998,2714300,12/21/2022 02:00:00 AM,12/21/2022 02:00:00 AM,548.0,2.4,1.703106e+10,1.703105e+10,6.0,...,103050.0,74366.38873,0.040466,North Center,35114.0,77950.66977,0.065840,0.000000,1,False
2999999,2999999,2999999,2719219,12/21/2022 02:15:00 AM,12/21/2022 02:30:00 AM,719.0,3.4,NaN,NaN,4.0,...,40494.0,49797.24946,0.059551,Irving Park,51940.0,38887.99043,0.080474,16.008538,1,True

In [29]:
# Checking the number of NA. Some minor absence from Tip, Trip Miles, and Trip seconds. We're deleting them. (around 3000 obs, or 0.1%)
df = df_2.dropna(subset=['Trip Seconds', 'Tip', 'Trip Miles', 'Fare', 'Tip_percent_PerRide','Trip Total'])

# Also dropping some stuff where values doesnt make sense
df = df[df['Tip_percent_PerRide'] < 1000]
df = df[df['Trip Seconds'] != 0]
df = df[(df['Trip Miles'] != 0) & (df['Trip Miles'] > 0.1)]

df = df.drop(['Unnamed: 0', 'Unnamed: 0.1', 'Unnamed: 0.1.1'], axis = 1)
df['Date2'] = pd.to_datetime(df['Date'], format='%Y/%m/%d')

df['traffic_condition'] = (df['Trip Miles']/df['Trip Seconds'])
df = df[df['traffic_condition'] <= 0.04]

df['traffic_condition_interval'] = pd.cut(df['traffic_condition'], 
                            bins=[ 0, 0.0025, 0.005, 0.0085, 0.0125, 0.0165, max(df['traffic_condition'])],
                             labels=["Very high traffic", "high traffic", "high-avg traffic", "avg traffic", 
                                     "light traffic","no traffic"])

# Extracting the weekdays
df['weekday'] = df['Date2'].dt.weekday

In [36]:
df.to_csv("D:\coding project\cs590\FinalDatav1.csv")